### ISSUE TITLE
Compile to python example 

### ISSUE THREAD

**Issue by AusIV** [pyga/parsley#16]
Watching your pycon talk and looking through the code base, I gather that it's possible to compile from peg into python using parsley, but after a couple hours of searching I have yet to figure out the right structure to pass to the writePython function. Could you put together an example in the documentation?

**Comment by davmlaw** [comment]
This is a 10 year old closed issue but this worked for me:

```
import os
from ometa.grammar import OMeta
from ometa.builder import writePython


grammar_file = "my_grammar.pymeta"
g = OMeta(open(grammar_file).read(), name="Grammar")
tree = g.parseGrammar("Grammar")
source = writePython(tree, "Grammar")

with open( "my_grammar.py", "w") as source_file:
    source_file.write(source)
```

Then to instantiate it:

```
from my_grammar import createParserClass

bindings = {} # whatever you need
grammar = parsley.wrapGrammar(createParserClass(ometa.runtime.OMetaGrammarBase, bindings))
```
